name: Test
on: [push]
jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
          only-new-issues: true

  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.14', '1.13' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ matrix.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - name: Test
        run: make test

      - name: Race
        run: make race
